fix(gh): more cleanup on abort

diff --git a/package-managers/__gh b/package-managers/__gh
--- a/package-managers/__gh
+++ b/package-managers/__gh
@@ -70,6 +70,8 @@ case "$subcommand" in
     if ask "Is this release correct?" Y; then
       false
     else
+      echo "Aborting..."
+      rm -r "${GITHUB_PACKAGES:?}/$host_package_identifier"
       exit 1
     fi
     
@@ -85,9 +87,13 @@ case "$subcommand" in
     fi
     
     cd "$GITHUB_PACKAGES/$host_package_identifier" || exit 1
-    gh release download -R "$host_package_identifier" "$selected_version" --pattern "$asset_pattern"
-    mkdir -p "$(dirname "$GITHUB_PACKAGE_VERSIONS/$host_package_identifier")"
-    echo "$selected_version" > "$GITHUB_PACKAGE_VERSIONS/$host_package_identifier"
+    gh release download -R "$host_package_identifier" "$selected_version" --pattern "$asset_pattern" || {
+      echo "Download failed. Aborting..."
+      rm -r "${GITHUB_PACKAGES:?}/$host_package_identifier"
+      [ -f "$GITHUB_PACKAGE_VERSIONS/$host_package_identifier" ] && rm "$GITHUB_PACKAGE_VERSIONS/$host_package_identifier"
+      rm "$GITHUB_PACKAGE_ASSET_PATTERNS/$host_package_identifier"
+      exit 1
+    }
 
     "$0" build "$host_package_identifier"
   )
